CREATE TABLE PC_UTILISATEUR (
    UTI_Id INT PRIMARY KEY AUTO_INCREMENT,
    UTI_Pseudo VARCHAR(255) NOT NULL UNIQUE,
    UTI_Mail VARCHAR(255) NOT NULL UNIQUE,
    UTI_Prenom VARCHAR(255),
    UTI_Nom VARCHAR(255),
    UTI_DateInscription DATE NOT NULL,
    UTI_TypeUser INT,
    UTI_Statut INT
);

CREATE TABLE PC_CATEGORIE (
    CAT_Id INT PRIMARY KEY AUTO_INCREMENT,
    CAT_Intitulé VARCHAR(255) NOT NULL,
    CAT_Detail TEXT
);

CREATE TABLE PC_INGREDIENT (
    ING_Id INT PRIMARY KEY AUTO_INCREMENT,
    ING_Intitule VARCHAR(255) NOT NULL,
    ING_Detail TEXT
);

CREATE TABLE PC_RECETTE (
    REC_Id INT PRIMARY KEY AUTO_INCREMENT,
    REC_Titre VARCHAR(255) NOT NULL,
    REC_Contenu TEXT NOT NULL,
    REC_Resum TEXT,
    CAT_Id INT,
    REC_DateInscription DATE NOT NULL,
    REC_Image VARCHAR(500),
    REC_DateCreation DATE NOT NULL,
    REC_DateModification DATE,
    UTI_Id INT,
    FOREIGN KEY (CAT_Id) REFERENCES PC_CATEGORIE(CAT_Id),
    FOREIGN KEY (UTI_Id) REFERENCES PC_UTILISATEUR(UTI_Id)
);

CREATE TABLE PC_RECETTE_INGREDIENT (
    REC_Id INT,
    ING_Id INT,
    PRIMARY KEY (REC_Id, ING_Id),
    FOREIGN KEY (REC_Id) REFERENCES PC_RECETTE(REC_Id),
    FOREIGN KEY (ING_Id) REFERENCES PC_INGREDIENT(ING_Id)
);

CREATE TABLE PC_TAG (
    TAG_Id INT PRIMARY KEY AUTO_INCREMENT,
    TAG_Intitule VARCHAR(255) NOT NULL
);

CREATE TABLE PC_RECETTE_TAG (
    REC_Id INT,
    TAG_Id INT,
    PRIMARY KEY (REC_Id, TAG_Id),
    FOREIGN KEY (REC_Id) REFERENCES PC_RECETTE(REC_Id),
    FOREIGN KEY (TAG_Id) REFERENCES PC_TAG(TAG_Id)
);
